import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import SiteHeader from "./(hoem)/components/SiteHeader";
import ThemeProviders from "./(hoem)/components/ThemeProviders";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
        )}
      >
        <div
          className={cn(
            "relative",
            "min-h-dvh",
            "flex flex-col",
            "bg-background"
          )}
        >
          <ThemeProviders>
            <SiteHeader />
            {children}
          </ThemeProviders>
        </div>
      </body>
    </html>
  );
}
